apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-express-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-express-app
  template:
    metadata:
      labels:
        app: sample-express-app
    spec:
      containers:
      - name: sample-express-app
        image: 656953382254.dkr.ecr.us-east-1.amazonaws.com/sample-express-app
        ports:
        - containerPort: 80
